### ISSUE TITLE
Registering multiple dataset URLs?

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#518]
We might need to add the ability to register several URLs for a single dataset in the Clearinghouse. Paris has the ACEF export files not as a single zip archive but as:

http://rameau.snv.jussieu.fr/4d4life/psyllist/AcceptedSpecies.csv
http://rameau.snv.jussieu.fr/4d4life/psyllist/Synonyms.csv
http://rameau.snv.jussieu.fr/4d4life/psyllist/NameReferencesLinks.csv
http://rameau.snv.jussieu.fr/4d4life/psyllist/References.csv
http://rameau.snv.jussieu.fr/4d4life/psyllist/SourceDatabase.csv
http://rameau.snv.jussieu.fr/4d4life/psyllist/Distribution.csv
http://rameau.snv.jussieu.fr/4d4life/psyllist/CommonNames.csv
http://rameau.snv.jussieu.fr/4d4life/psyllist/AcceptedInfraSpecificTaxa.csv

**Comment by mdoering** [comment]
Hm, possible but causing quite some problem. Also if we want to down the line use the GBIF registry. Could we instead create some virtual archive tool that creates the zip on the fly if given a base URL like http://rameau.snv.jussieu.fr/4d4life/psyllist.zip ?

**Comment by gdower** [comment]
My other thought might be registering it as an acef file of URLs? e.g. a psyllist.acef file containing the above links?

**Comment by mdoering** [comment]
interesting, yes, thats doable. An ACEF archive with each file just having the URL as kind of a redirect as the content - that would be simple!

Or a generic YAML that maps each local file to a URL like this:

```
format: ACEF
AcceptedSpecies.csv: http://rameau.snv.jussieu.fr/4d4life/psyllist/AcceptedSpecies.csv
Synonyms.csv: http://rameau.snv.jussieu.fr/4d4life/psyllist/Synonyms.csv
NameReferencesLinks.csv: http://rameau.snv.jussieu.fr/4d4life/psyllist/NameReferencesLinks.csv
References.csv: http://rameau.snv.jussieu.fr/4d4life/psyllist/References.csv
SourceDatabase.csv: http://rameau.snv.jussieu.fr/4d4life/psyllist/SourceDatabase.csv
Distribution.csv: http://rameau.snv.jussieu.fr/4d4life/psyllist/Distribution.csv
CommonNames.csv: http://rameau.snv.jussieu.fr/4d4life/psyllist/CommonNames.csv
AcceptedInfraSpecificTaxa.csv: http://rameau.snv.jussieu.fr/4d4life/psyllist/AcceptedInfraSpecificTaxa.csv
```

**Comment by mdoering** [comment]
we could even override the header or character encoding with defaults:

```
format: ACEF
AcceptedSpecies.csv: 
  url: http://rameau.snv.jussieu.fr/4d4life/psyllist/AcceptedSpecies.csv
  encoding: UTF-8
  header:
    - AcceptedTaxonID
    - Kingdom
    - Phylum
    - Class
Synonyms.csv: http://rameau.snv.jussieu.fr/4d4life/psyllist/Synonyms.csv
NameReferencesLinks.csv: http://rameau.snv.jussieu.fr/4d4life/psyllist/NameReferencesLinks.csv
References.csv: http://rameau.snv.jussieu.fr/4d4life/psyllist/References.csv
SourceDatabase.csv: http://rameau.snv.jussieu.fr/4d4life/psyllist/SourceDatabase.csv
Distribution.csv: http://rameau.snv.jussieu.fr/4d4life/psyllist/Distribution.csv
CommonNames.csv: http://rameau.snv.jussieu.fr/4d4life/psyllist/CommonNames.csv
AcceptedInfraSpecificTaxa.csv: http://rameau.snv.jussieu.fr/4d4life/psyllist/AcceptedInfraSpecificTaxa.csv
```

**Comment by gdower** [comment]
Psyllist fails to import the with [stacktrace](https://logs.gbif.org/app/kibana#/context/AWyLa2lBHCKcR6PFXu26/logs/AW3eq_spHCKcR6PFwYl0?_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa2lBHCKcR6PFXu26,key:environment,negate:!f,type:phrase,value:col-dev),query:(match:(environment:(query:col-dev,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa2lBHCKcR6PFXu26,key:level,negate:!t,type:phrase,value:DEBUG),query:(match:(level:(query:DEBUG,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa2lBHCKcR6PFXu26,key:level,negate:!t,type:phrase,value:INFO),query:(match:(level:(query:INFO,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa2lBHCKcR6PFXu26,key:dataset,negate:!f,type:phrase,value:'2050'),query:(match:(dataset:(query:'2050',type:phrase))))))):

```
org.col.importer.NormalizationFailedException$SourceInvalidException: acef:AcceptedSpecies file required but missing from /home/col/bin/dev/scratch/2050/source
	at org.col.csv.CsvReader.requireSchema(CsvReader.java:167)
	at org.col.importer.acef.AcefReader.validate(AcefReader.java:63)
	at org.col.csv.CsvReader.<init>(CsvReader.java:91)
	at org.col.importer.acef.AcefReader.<init>(AcefReader.java:22)
	at org.col.importer.acef.AcefReader.from(AcefReader.java:37)
	at org.col.importer.acef.AcefInserter.<init>(AcefInserter.java:47)
	at org.col.importer.Normalizer.insertData(Normalizer.java:806)
	at org.col.importer.Normalizer.call(Normalizer.java:75)
	at org.col.importer.ImportJob.importDataset(ImportJob.java:193)
	at org.col.importer.ImportJob.run(ImportJob.java:118)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

It's probably because of the ACEF vocab not matching, but I'm not going to open separate ticket for now since this could be resolved with the yaml config file.

Here's the [zip archive that I manually made](https://github.com/Sp2000/colplus-backend/files/3744015/psyllist.zip).

**Comment by mdoering** [comment]
> Required term acef:SpeciesEpithet missing. Ignore file /home/col/bin/prod/scratch/30388/source/AcceptedSpecies.csv

**Comment by gdower** [comment]
Here's the YAML I used to use for mapping table names and headings:

```YAML
gsd:
    db_data_format: 'csv'
    db_id: 140
    db_prefix: 'fer-'
    db_name: 'WorldFerns'

table_names:
    GM_AcceptedSpecies: 'AcceptedSpecies'
    GM_AcceptedInfraSpecificTaxa: 'AcceptedInfraSpecificTaxa'
    GM_CommonNames: 'CommonNames'
    GM_Distribution: 'Distribution'
    GM_NameReferenceLinks: 'NameReferencesLinks'
    GM_References: 'References'
    GM_SourceDatabase: 'SourceDatabase'
    GM_Synonyms: 'Synonyms'

tables:
    GM_AcceptedSpecies:
        GM_ACC_AcceptedTaxonID: 'AcceptedTaxonID'
        GM_ACC_Kingdom: 'Kingdom'
        GM_ACC_Phylum: 'Phylum'
        GM_ACC_Class: 'Class'
        GM_ACC_Order: 'Order'
        GM_ACC_SuperFamily: 'SuperFamily'
        GM_ACC_Family: 'Family'
        GM_ACC_Genus: 'Genus'
        GM_ACC_SubGenusName: 'SubgenusName'
        GM_ACC_SpeciesEpithet: 'SpeciesEpithet'
        GM_ACC_AuthorString: 'AuthorString'
        GM_ACC_GSDNameStatus: 'GSDNameStatus'
        GM_ACC_Sp2000NameStatus: 'Sp2000NameStatus'
        GM_ACC_IsExtinct: 'IsExtinct'
        GM_ACC_HasPreHolocene: 'HasPreHolocene'
        GM_ACC_HasModern: 'HasModern'
        GM_ACC_LifeZone: 'LifeZone'
        GM_ACC_AdditionalData: 'AdditionalData'
        GM_ACC_LTSSPecialist: 'LTSSpecialist'
        GM_ACC_LTSDate: 'LTSDate'
        GM_ACC_SpeciesURL: 'SpeciesURL'
        GM_ACC_GSDTaxonGUID: 'GSDTaxonGUID'
        GM_ACC_GSDNameGUID: 'GSDNameGUID'

    GM_AcceptedInfraSpecificTaxa:
        GM_INFRA_AcceptedTaxonID: 'AcceptedTaxonID'
        GM_INFRA_ParentSpeciesID: 'ParentSpeciesID'
        GM_INFRA_InfraSpeciesEpithet: 'InfraSpecies'
        GM_INFRA_InfraSpeciesAuthorString: 'InfraSpeciesAuthorString'
        GM_INFRA_InfraSpeciesMarker: 'InfraSpeciesMarker'
        GM_INFRA_GSDNameStatus: 'GSDNameStatus'
        GM_INFRA_Sp2000NameStatus: 'Sp2000NameStatus'
        GM_INFRA_IsExtinct: 'IsExtinct'
        GM_INFRA_HasPreHolocene: 'HasPreHolocene'
        GM_INFRA_HasModern: 'HasModern'
        GM_INFRA_LifeZone: 'LifeZone'
        GM_INFRA_AdditionalData: 'AdditionalData'
        GM_INFRA_LTSSpecialist: 'LTSSpecialist'
        GM_INFRA_LTSDate: 'LTSDate'
        GM_INFRA_InfraSpeciesURL: 'InfraSpeciesURL'
        GM_INFRA_GSDTaxonGUID: 'GSDTaxonGUID'
        GM_INFRA_GSDNameGUID: 'GSDNameGUID'

    GM_CommonNames:
        GM_COM_AcceptedTaxonID: 'ID'
        GM_COM_CommonName: 'CommonName'
        GM_COM_TransliteratedName: 'TransliteratedName'
        GM_COM_Language: 'Language'
        GM_COM_Country: 'Country'
        GM_COM_Area: 'Area'
        GM_COM_ReferenceID: 'ReferenceID'
        
    GM_Distribution:
        GM_DIST_AcceptedTaxonID: 'AcceptedTaxonID'
        GM_DIST_DistributionElement: 'DistributionElement'
        GM_DIST_StandardInUse: 'StandardInUse'
        GM_DIST_DistributionStatus: 'DistributionStatus'
        
    GM_NameReferenceLinks:
        GM_REFLINK_ID: 'ID'
        GM_REFLINK_ReferenceType: 'ReferenceType'
        GM_REFLINK_ReferenceID: 'ReferenceID'
        
    GM_References:
        GM_REF_ReferenceID: 'ReferenceID'
        GM_REF_Authors: 'Authors'
        GM_REF_Year: 'Year'
        GM_REF_Title: 'Title'
        GM_REF_Details: 'Details'
        
    GM_SourceDatabase:
        GM_DB_DatabaseFullName: 'DatabaseFullName'
        GM_DB_DatabaseShortName: 'DatabaseShortName'
        GM_DB_DatabaseVersion: 'DatabaseVersion'
        GM_DB_ReleaseDate: 'ReleaseDate'
        GM_DB_AuthorsEditors: 'AuthorsEditors'
        GM_DB_TaxonomicCoverage: 'TaxonomicCoverage'
        GM_DB_GroupNameInEnglish: 'GroupNameInEnglish'
        GM_DB_Abstract: 'Abstract'
        GM_DB_Organisation: 'Organisation'
        GM_DB_HomeURL: 'HomeURL'
        GM_DB_Coverage: 'Coverage'
        GM_DB_Completeness: 'Completeness'
        GM_DB_Confidence: 'Confidence'
        GM_DB_LogoFileName: 'LogoFileName'
        GM_DB_ContactPerson: 'ContactPerson'
        
    GM_Synonyms:
        GM_SYN_ID: 'ID'
        GM_SYN_AcceptedTaxonID: 'AcceptedTaxonID'
        GM_SYN_Genus: 'Genus'
        GM_SYN_SubGenusName: 'SubGenusName'
        GM_SYN_SpeciesEpithet: 'SpeciesEpithet'
        GM_SYN_AuthorString: 'AuthorString'
        GM_SYN_InfraSpeciesMarker: 'InfraSpeciesMarker'
        GM_SYN_InfraSpeciesAuthorString: 'InfraSpeciesAuthorString'
        GM_SYN_InfraSpecies: 'InfraSpeciesEpithet'
        GM_SYN_GSDNameStatus: 'GSDNameStatus'
        GM_SYN_Sp2000NameStatus: 'Sp2000NameStatus'
        GM_SYN_GSDNameGUID: 'GSDNameGUID'
        
transformations:
    alter_syn_table: 'ALTER TABLE Synonyms MODIFY AuthorString varchar(200) null;'
    copy_syn_authors: 'UPDATE Synonyms SET AuthorString=InfraSpeciesAuthorString WHERE InfraSpeciesEpithet IS NULL OR InfraSpeciesEpithet="";'
    del_syn_infra_auth: 'UPDATE Synonyms SET InfraSpeciesAuthorString=NULL WHERE InfraSpeciesEpithet IS NULL OR InfraSpeciesEpithet="";'
```

**Comment by gdower** [comment]
The [same problem](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa2lBHCKcR6PFXu26,key:environment,negate:!f,type:phrase,value:col-dev),query:(match:(environment:(query:col-dev,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa2lBHCKcR6PFXu26,key:level,negate:!t,type:phrase,value:DEBUG),query:(match:(level:(query:DEBUG,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa2lBHCKcR6PFXu26,key:level,negate:!t,type:phrase,value:INFO),query:(match:(level:(query:INFO,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa2lBHCKcR6PFXu26,key:dataset,negate:!f,type:phrase,value:'2051'),query:(match:(dataset:(query:'2051',type:phrase))))),index:AWyLa2lBHCKcR6PFXu26,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))) occurs with WoRMs exporter with the SpeciesEpithet column.

**Comment by mdoering** [comment]
ok, comitting this implementation now:

```
format: ACEF
files:
  - name: AcceptedSpecies.csv
    url: http://rameau.snv.jussieu.fr/4d4life/psyllist/AcceptedSpecies.csv
    encoding: UTF-8
    delimiter: ","
    quotation: "\""
    header:
     - acef:AcceptedTaxonID
     - acef:Kingdom
     - acef:Phylum
     - acef:Class
  - name: Synonyms.csv
    url: http://rameau.snv.jussieu.fr/4d4life/psyllist/Synonyms.csv
  - name: NameReferencesLinks.csv
    url: http://rameau.snv.jussieu.fr/4d4life/psyllist/NameReferencesLinks.csv
  - name: References.csv
    url: http://rameau.snv.jussieu.fr/4d4life/psyllist/References.csv
  - name: SourceDatabase.csv
    url: http://rameau.snv.jussieu.fr/4d4life/psyllist/SourceDatabase.csv
  - name: Distribution.csv
    url: http://rameau.snv.jussieu.fr/4d4life/psyllist/Distribution.csv
  - name: CommonNames.csv
    url: http://rameau.snv.jussieu.fr/4d4life/psyllist/CommonNames.csv
  - name: AcceptedInfraSpecificTaxa.csv
    url: http://rameau.snv.jussieu.fr/4d4life/psyllist/AcceptedInfraSpecificTaxa.csv
```

Basically the files must have a `name` and a `url` attribute. All others have defaults as given above.
If a header list is given the first line of the remote file will be replaced by the given terms using the delimiter and quotation.
